Projects/Youtube/django_app/Youtube_2/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^video/', include('video.urls')),
    url(r'^$', views.index, name='index'),
]

Projects/Youtube/django_app/video/urls.py
from django.conf.urls import url

from . import views

app_name = 'video'
urlpatterns = [
    url(r'^search/$', views.search, name='search'),
    url(r'^bookmark/$', views.bookmark_list, name='bookmark_list'),
    url(r'^bookmark/add/$', views.bookmark_add, name='bookmark_add'),
]

Projects/Youtube/django_app/member/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class MyUser(AbstractUser):
    bookmark_videos = models.ManyToManyField(
        'video.Video',
        blank=True,
    )

Projects/Youtube/django_app/video/models.py
from django.db import models


class Video(models.Model):
    title = models.CharField(max_length=300)
    description = models.TextField(blank=True)
    youtube_id = models.CharField(unique=True, max_length=100)
    url_thumbnail = models.URLField(max_length=100, blank=True)
    published_date = models.DateTimeField()

    def __str__(self):
        return self.title

Projects/Youtube/django_app/Youtube_2/views.py
from django.shortcuts import redirect


def index(request):
    return redirect('video:search')

Projects/Youtube/django_app/member/views.py
from django.shortcuts import render

# Create your views here.

Projects/Youtube/django_app/video/views.py
import json

import requests
from dateutil.parser import parse
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from utils.settings import get_settings
from video.models import Video


def search_from_youtube(keyword, page_token=None):
    youtube_api_key = get_settings()['youtube']['API_KEY']
    params = {
        'part': 'snippet',
        'q': keyword,
        'maxResults': 10,
        'type': 'video',
        'key': youtube_api_key,
    }
    # 페이지 토큰값이 전달되었을 때만 params에 해당 내용을 추가해서 요
    if page_token:
        params['pageToken'] = page_token
    r = requests.get('https://www.googleapis.com/youtube/v3/search', params=params)
    result = r.text
    result_dict = json.loads(result)
    return result_dict


def search(request):
    # 검색결과를 담을 리스트
    videos = []
    context = {
        'videos': videos
    }

    # GET parameters에 keyword값이 왔을때만 검색결과에 내용이 추가됨
    keyword = request.GET.get('keyword', '').strip()
    page_token = request.GET.get('page_token')

    if keyword != '':
        # 검색 결과를 받아옴
        search_result = search_from_youtube(keyword, page_token)

        # 검색결과에서 이전/다음 토큰, 전체 결과 개수를 가져와
        # 템플릿에 전달할 context 객체에 할당
        next_page_token = search_result.get('nextPageToken')
        prev_page_token = search_result.get('prevPageToken')
        total_results = search_result['pageInfo'].get('totalResults')
        items = search_result['items']
        context['next_page_token'] = next_page_token
        context['prev_page_token'] = prev_page_token
        context['total_results'] = total_results
        context['keyword'] = keyword

        # 검색 결과에서 'items' 키를 갖는 list를 items 변수에 할당 후 loop
        for item in items:
            published_date_str = item['snippet']['publishedAt']

            # 실제로 사용할 데이터
            youtube_id = item['id']['videoId']
            title = item['snippet']['title']
            description = item['snippet']['description']
            published_date = parse(published_date_str)
            url_thumbnail = item['snippet']['thumbnails']['high']['url']

            # 현재 item을 dict로 정리
            cur_item_dict = {
                'title': title,
                'description': description,
                'published_date': published_date,
                'youtube_id': youtube_id,
                'url_thumbnail': url_thumbnail,
            }
            videos.append(cur_item_dict)
    return render(request, 'video/search.html', context)


@login_required
def bookmark_add(request):
    if request.method == 'POST':
        title = request.POST['title']
        description = request.POST['description']
        youtube_id = request.POST['youtube_id']
        url_thumbnail = request.POST['url_thumbnail']
        published_date_str = request.POST['published_date']
        published_date = parse(published_date_str)
        prev_path = request.POST['path']

        defaults = {
            'title': title,
            'description': description,
            'published_date': published_date,
            'url_thumbnail': url_thumbnail,
        }
        video, _ = Video.objects.get_or_create(
            defaults=defaults,
            youtube_id=youtube_id
        )
        request.user.bookmark_videos.add(video)
        return redirect(prev_path)


@login_required
def bookmark_list(request):
    bookmarks = request.user.bookmark_videos.all()
    context = {
        'bookmarks': bookmarks,
    }
    return render(request, 'video/bookmark_list.html', context)

Projects/Youtube/django_app/templates/common/base.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>YouTube</title>
</head>
<body>
<div id="wrap">
    <h1>
        <a href="{% url 'index' %}">YouTube Bookmark</a>
    </h1>
    <a href="{% url 'video:bookmark_list' %}">My Bookmark</a>

    <div class="content-container">
        {% block content %}
        {% endblock %}
    </div>
</div>
</body>
</html>

Projects/Youtube/django_app/templates/video/bookmark_list.html
{% extends 'common/base.html' %}

{% block content %}
    <div class="bookmark-list-container">
        <ul class="video-list">
            {% for video in bookmarks %}
            <li class="video-item">
                <img src="{{ video.url_thumbnail }}" alt="" class="item-thumbnail">
                <div class="item-container">
                    <div class="vcenter ellipsis">
                        <a href="" class="item-title">{{ video.title }}</a>
                        <p class="item-desc">{{ video.description }}</p>
                        <p class="item-date">{{ video.published_date }}</p>
                    </div>
                </div>
            </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

Projects/Youtube/django_app/templates/video/search.html
{% extends 'common/base.html' %}
{% block content %}
<div class="search-container">
    <form action="">
        <input type="text" name="keyword">
        <button type="submit" class="btn">Search</button>
    </form>

    <ul class="video-list">
        {% for video in videos %}
        <li class="video-item">
            <img src="{{ video.url_thumbnail }}" alt="" class="item-thumbnail">
            <div class="item-content">
                <div class="vcenter">
                    <a href="https://www.youtube.com/watch?v={{ video.youtube_id }}" class="item-title">{{ video.title }}</a>
                    <p class="item-desc">{{ video.description }}</p>
                    <p class="item-date">{{ video.published_date }}</p>

                    <form action="{% url 'video:bookmark_add' %}" method="POST">{% csrf_token %}
                        <input type="hidden" name="title" value="{{ video.title }}">
                        <input type="hidden" name="description" value="{{ video.description }}">
                        <input type="hidden" name="published_date" value="{{ video.published_date }}">
                        <input type="hidden" name="youtube_id" value="{{ video.youtube_id }}">
                        <input type="hidden" name="url_thumbnail" value="{{ video.url_thumbnail }}">
                        <input type="hidden" name="path" value="{{ request.get_full_path }}">
                        <button type="submit" class="btn">Add Bookmark</button>
                    </form>
                </div>
            </div>
            </li>
        {% endfor %}
    </ul>
    <div>
        {% if prev_page_token %}
        <form action="">
            <input type="hidden" name="keyword" value="{{ keyword }}">
            <input type="hidden" name="page_token" value="{{ prev_page_token }}">
            <button type="submit" class="btn">Prev</button>
        </form>
        {% endif %}

        {% if next_page_token %}
        <form action="">
            <input type="hidden" name="keyword" value="{{ keyword }}">
            <input type="hidden" name="page_token" value="{{ next_page_token }}">
            <button type="submit" class="btn">Next</button>
        </form>
        {% endif %}
    </div>
</div>
{% endblock %}